services:
  - type: web
    name: agritwist-n8n
    runtime: image

    image:
      url: docker.io/n8nio/n8n:latest

    plan: free

    envVars:
      - key: PORT
        value: 5678

      - key: N8N_PORT
        value: 5678

      - key: N8N_PROTOCOL
        value: https

      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      - key: DB_TYPE
        value: postgresdb

      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: agritwist-n8n-db
          property: host

      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: agritwist-n8n-db
          property: port

      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: agritwist-n8n-db
          property: database

      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: agritwist-n8n-db
          property: user

      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: agritwist-n8n-db
          property: password

databases:
  - name: agritwist-n8n-db
    plan: free
